PresentacionAdmin/Controllers/MantenimientoController.cs
using Entidad;
using Negocios;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentacionAdmin.Controllers
{
    public class MantenimientoController : Controller
    {
        public ActionResult Mantenimientos()
        {
            return View();
        }
        
        public ActionResult Categorias()
        {
            return View();
        }
        
        public ActionResult Marcas()
        {
            return View();
        }
        
        public ActionResult Productos()
        {
            return View();
        }

        //categorias
        #region categoria
        [HttpGet]
        public JsonResult ListarCategorias()
        {
            List<Categoria> oLista = new List<Categoria>();
            oLista = new N_Categorias().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarCategorias(Categoria objeto)
        {
            object resultado;
            string mensaje = string.Empty;

            if (objeto.idcategoria == 0)
            {
                resultado = new N_Categorias().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new N_Categorias().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarCategorias(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new N_Categorias().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        // marcas
        #region marca
        [HttpGet]
        public JsonResult ListarMarcas()
        {
            List<Marca> oLista = new List<Marca>();
            oLista = new N_Marcas().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarMarcas(Marca objeto)
        {
            object resultado;
            string mensaje = string.Empty;

            if (objeto.idmarca == 0)
            {
                resultado = new N_Marcas().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new N_Marcas().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarMarcas(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new N_Marcas().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        //producto
        #region producto
        [HttpGet]
        public JsonResult ListarProductos()
        {
            List<Producto> oLista = new List<Producto>();
            oLista = new N_productos().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarProductos(string objeto, HttpPostedFileBase archivoimg)
        {
            string mensaje = string.Empty;

            bool operacionexitosa = true;
            bool guardarimg = true;

            Producto oProducto = new Producto();
            oProducto = JsonConvert.DeserializeObject<Producto>(objeto);

            decimal precio;
            if (decimal.TryParse(oProducto.precioTexto, NumberStyles.AllowDecimalPoint, new CultureInfo("es-PE"), out precio))
            {
                oProducto.precio = precio;
            } else
            {
                return Json(new { operacionExitosa =false, mensaje = "El formato del precio debe ser ##.##" }, JsonRequestBehavior.AllowGet);
            }

            if (oProducto.idproducto == 0)
            {
                int idprodgenerado = new N_productos().Registrar(oProducto, out mensaje);
                if (idprodgenerado != 0)
                {
                    oProducto.idproducto = idprodgenerado;
                } else
                {
                    operacionexitosa = false;
                }
            }
            else
            {
                operacionexitosa = new N_productos().Editar(oProducto, out mensaje);
            }

            if(operacionexitosa)
            {
                if(archivoimg != null)
                {
                    string rutaguardar = ConfigurationManager.AppSettings["ServidorFotos"];
                    string extension = Path.GetExtension(archivoimg.FileName);
                    string nombreimg = string.Concat(oProducto.idproducto.ToString(), extension);

                    try
                    {
                        archivoimg.SaveAs(Path.Combine(rutaguardar, nombreimg));
                    } catch (Exception ex)
                    {
                        string msg = ex.Message;
                        guardarimg = false;
                    }

                    if (guardarimg)
                    {
                        oProducto.rutaimg = rutaguardar;
                        oProducto.nombreimg = nombreimg;
                        bool rpta = new N_productos().GuardarImg(oProducto, out mensaje);
                    } else
                    {
                        mensaje = "Se guardo el producto pero se encontraron problemas en la imagen 🌄";
                    }
                }
            }

            return Json(new { operacionExitosa = operacionexitosa, idgenerado = oProducto.idproducto, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult imgProductos(int id)
        {
            bool conversion;
            Producto oProducto = new N_productos().Listar().Where(p => p.idproducto == id).FirstOrDefault();

            string textoBase64 = N_Recursos.ConvertirBase64(Path.Combine(oProducto.rutaimg, oProducto.nombreimg), out conversion);
            return Json(new
            {
                conversion = conversion,
                textobase64 = textoBase64,
                extension = Path.GetExtension(oProducto.nombreimg)
            }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult EliminarProductos(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new N_productos().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion


    }
}

PresentacionAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sistema Farmacia</title>
    <link rel="shortcut icon" href="~/assets/images/icono.png">
    @Styles.Render("~/Content/css")
    @*Scripts.Render("~/bundles/modernizr")*@
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-light" style="background: #b6b6b6; user-select: none;">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3 sidebar-divider" href="#">
            <!--FAMISALUD-->
            <img class="img-logo" src="~/assets/images/logo.png" style="width: 140px;">
        </a>

        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown text-bg-success rounded-2">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline small" style="color: #ebe1c9;">Douglas McGee</span>
                    <i class="fas fa-user fa-fw"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-user fa-sm"></i>
                            &nbsp;
                            Perfil
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="#!">
                            <i class="fas fa-cogs fa-sm"></i>
                            &nbsp;
                            Configuracion
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-user-lock fa-sm"></i>
                            &nbsp;
                            Restablecer Contraseña
                        </a>
                    </li>
                    <li><hr class="dropdown-divider" /></li>
                    <li>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-sign-out-alt fa-sm"></i>
                            &nbsp;
                            Cerrar Sesion
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>

    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark text-primary" id="sidenavAccordion" style="background: #4e73df; user-select: none;">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="sb-sidenav-menu-heading text-light text-decoration-none" href="@Url.Action("Dashboard", "Home")">
                            📊 Dashboard
                        </a>
                        <a class="nav-link collapse" href="@Url.Action("Index", "Home")">
                            <!--<div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>-->
                            🏡
                            Inicio
                        </a>
                        <a class="nav-link" href="@Url.Action("Usuarios", "Home")">
                            <!--<div class="sb-nav-link-icon"><i class="fas fa-user-friends"></i></div>-->
                            🙋
                            Usuarios
                        </a>

                        <a class="sb-sidenav-menu-heading text-light text-decoration-none"  href="@Url.Action("Mantenimientos", "Mantenimiento")">
                                🛠️ Mantenimientos
                        </a>
                        <a class="nav-link" href="@Url.Action("Categorias", "Mantenimiento")">
                            <!--<div class="sb-nav-link-icon"><i class="fas fa-grip-horizontal"></i></div>-->
                            🔠
                            Categorias
                        </a>
                        <a class="nav-link" href="@Url.Action("Marcas", "Mantenimiento")">
                            <!--<div class="sb-nav-link-icon"><i class="fas fa-tags"></i></div>-->
                            🏷️
                            Marcas
                        </a>
                        <a class="nav-link" href="@Url.Action("Productos", "Mantenimiento")">
                            <!--<div class="sb-nav-link-icon"><i class="fas fa-boxes"></i></div>-->
                            📦
                            Productos
                        </a>
                    </div>
                </div>

                <div class="sb-sidenav-footer text-light">
                    <div class="small">Conectado como:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>

        <div id="layoutSidenav_content">
            <main>
                <!--comiendo -->
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
                <!--fin comienzo-->
            </main>

            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Clinica Famisalud 2023</div>
                        <div>
                            <a href="https://www.famisalud.com.pe/web/index.php?view=politica-privacidad" class="btn btn-outline-primary btn-sm" target="_blank">Politica y Privacidad</a>
                            &middot;
                            <a href="https://www.famisalud.com.pe/web/index.php?view=terminos-condiciones" class="btn btn-outline-primary btn-sm" target="_blank">Terminos &amp; Condiciones</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>